### ISSUE TITLE
Handle insufficient space to create tables better 

### ISSUE THREAD

**Issue by james-allan** [woocommerce/action-scheduler#419]
Preface: This is likely to be a rare case but I figured I would raise it in case there's something we can do to prevent this in future.

I was working on a site that was getting errors after upgrading to 3.0. The original error was: 

```
Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: Table '.wp3zd0_actionscheduler_actions' doesn't exist in /var/www/html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 
Stack trace: 
#0 /var/www/html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(225): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL)
#1 /var/www/html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) 
#2 /var/www/html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) 
#3 /var/www/html/wp-content/plugins/woocommerce-subscri in /var/www/html/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44
```

Essentially, the tables didn't exist. There was an investigation and it turned out in the end that Action Scheduler thought the tables existed because the schema options were set but because the site didn't enough disk space, creating the tables was failing. 

Is this something we could have prevented? As far as I know, creating the tables was just silently failing and the errors only came from trying to access the tables.

**Comment by rrennick** [comment]
> Is this something we could have prevented?

`dbDelta` returns an array of messages indicating what it attempted to do vs any results messages. We would need to look at alternative way of verifying that it was successful.
