### ISSUE TITLE
Mailchimp for Woocommerce is saying its Wordpress' fault

### ISSUE THREAD

**Issue by MarcusFuto** [woocommerce/action-scheduler#482]
I am lately getting a lot of errors on the site. Mailchimp for Woocommerce is saying I should report it here and that they cannot do anything (see this post https://wordpress.org/support/topic/action-scheduler/) : 

[09-Mar-2020 12:37:12 UTC] PHP Notice:  Undefined property: wpdb::$actionscheduler_actions in /var/www/vhosts/ringsofsweden.com/httpdocs/wp-includes/wp-db.php on line 659
[09-Mar-2020 12:37:12 UTC] WordPress databasfel för Table 'admin_ringso5_latest.a' doesn't exist förfrågan SELECT a.action_id FROM  a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 skapat av shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[09-Mar-2020 12:37:12 UTC] PHP Notice:  Undefined property: wpdb::$actionscheduler_actions in /var/www/vhosts/ringsofsweden.com/httpdocs/wp-includes/wp-db.php on line 659
[09-Mar-2020 12:37:12 UTC] WordPress databasfel för Table 'admin_ringso5_latest.a' doesn't exist förfrågan SELECT a.action_id FROM  a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1 skapat av shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[09-Mar-2020 12:37:12 UTC] PHP Notice:  Undefined property: wpdb::$actionscheduler_actions in /var/www/vhosts/ringsofsweden.com/httpdocs/wp-includes/wp-db.php on line 659
[09-Mar-2020 12:37:12 UTC] WordPress databasfel för Table 'admin_ringso5_latest.a' doesn't exist förfrågan SELECT a.action_id FROM  a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 skapat av shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[09-Mar-2020 12:37:12 UTC] PHP Notice:  Undefined property: wpdb::$actionscheduler_actions in /var/www/vhosts/ringsofsweden.com/httpdocs/wp-includes/wp-db.php on line 659
[09-Mar-2020 12:37:12 UTC] WordPress databasfel för Table 'admin_ringso5_latest.a' doesn't exist förfrågan SELECT a.action_id FROM  a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1 skapat av shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[09-Mar-2020 12:37:12 UTC] PHP Notice:  Undefined property: wpdb::$actionscheduler_groups in /var/www/vhosts/ringsofsweden.com/httpdocs/wp-includes/wp-db.php on line 659
[09-Mar-2020 12:37:12 UTC] WordPress databasfel för You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE slug='action-scheduler-migration'' at line 1 förfrågan SELECT group_id FROM  WHERE slug='action-scheduler-migration' skapat av shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->get_group_id
[09-Mar-2020 12:37:12 UTC] PHP Notice:  Undefined property: wpdb::$actionscheduler_groups in /var/www/vhosts/ringsofsweden.com/httpdocs/wp-includes/wp-db.php on line 659
[09-Mar-2020 12:37:12 UTC] WordPress databasfel för Incorrect table name '' förfrågan SHOW FULL COLUMNS FROM `` skapat av shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->get_group_id, ActionScheduler_DBStore->create_group
[09-Mar-2020 12:37:12 UTC] PHP Notice:  Undefined property: wpdb::$actionscheduler_actions in /var/www/vhosts/ringsofsweden.com/httpdocs/wp-includes/wp-db.php on line 659
[09-Mar-2020 12:37:12 UTC] WordPress databasfel för Incorrect table name '' förfrågan SHOW FULL COLUMNS FROM `` skapat av shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action
[09-Mar-2020 12:37:12 UTC] PHP Fatal error:  Uncaught RuntimeException: Error saving action: Error saving action: Incorrect table name '' in /var/www/vhosts/ringsofsweden.com/httpdocs/wp-content/plugins/mailchimp-for-woocommerce/includes/vendor/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44
Stack trace:
#0 /var/www/vhosts/ringsofsweden.com/httpdocs/wp-content/plugins/mailchimp-for-woocommerce/includes/vendor/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(225): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL)
#1 /var/www/vhosts/ringsofsweden.com/httpdocs/wp-content/plugins/mailchimp-for-woocommerce/includes/vendor/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action))
#2 /var/www/vhosts/ringsofsweden.com/httpdocs/wp-content/plugins/mailchimp-for-woocommerce/includes/vendor/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionSchedu in /var/www/vhosts/ringsofsweden.com/httpdocs/wp-content/plugins/mailchimp-for-woocommerce/includes/vendor/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44

Hope someone can take a look at this. 

Kind regards,

Marcus

**Comment by rrennick** [comment]
@MarcusFuto Sorry to hear you are having an issue. Can you go through the conflict testing outlined in https://docs.woocommerce.com/document/how-to-test-for-conflicts/ ?

We are trying to compile a list of extensions that have conflicts and would appreciate if you would let us know what you find.

**Comment by MarcusFuto** [comment]
Hello, went through the process and the only thing that helped was deactivating the Mailchimp for Woocommerce plugin by Mailchimp. 

I will keep it deactivated, but it is strange that they say it has to do with you guys. 

Here is the ticket I opened with them. If you have any suggestions please let me know. 

https://wordpress.org/support/topic/problems-displaying-site-correctly-when-plugin-is-active/

Thanks!

**Comment by rrennick** [comment]
> went through the process and the only thing that helped was deactivating the Mailchimp for Woocommerce plugin by Mailchimp.

I have been doing some investigation work with the MC extension folks. There are no issues with it  active on my dev site. We are aware of a small number of plugins that load Action Scheduler incorrectly which cause the specific error you are seeing.

As this is an issue with an unidentified plugin vs Action Scheduler, I'll close. @MarcusFuto If you'd like to post your list of active extensions, I might recognize one with a known issue.

**Comment by degregar** [comment]
Hi,
I'm experiencing the same issue with action scheduler. The plugin causing problems is: woocommerce dotpay: https://github.com/dotpay/WooCommerce2

I've crossed this issue trying to solve problem with REST API:

> The REST API request failed due to an error.
Error: [] cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received

**Comment by rrennick** [comment]
@degregar Thanks for letting us know :)

**Comment by MarcusFuto** [comment]
Here is a list of my plugins:

Redux Framework |   | by Team Redux – 3.6.17
-- | -- | --
WPML Multilingual CMS |   | by OnTheGoSystems – 4.3.10
Yoast SEO Multilingual |   | by OnTheGoSystems – 1.0.3
Remember_Last_Choice_WPML |   | by – 1.2
Ultimate Addons for WPBakery Page Builder |   | by Brainstorm Force – 3.19.3
Antispam Bee |   | by pluginkollektiv – 2.9.1
CF7 Google Sheet Connector |   | by WesternDeal – 4.1
Cloudflare |   | by John Wineman, Furkan Yilmaz, Junade Ali (Cloudflare Team) – 3.4.1
CMB2 |   | by CMB2 team – 2.7.0
Contact Form 7 Extension For Mailchimp |   | by Renzo Johnson – 0.5.14
Contact Form 7 |   | by Takayuki Miyoshi – 5.1.7
Cookie Notice |   | by dFactory – 1.2.50
Enhanced E-commerce for Woocommerce store |   | by Tatvic – 2.3.3
Social Reviews & Recommendations |   | by RichPlugins – 1.6.8
Head, Footer and Post Injections |   | by Stefano Lissa – 3.1.6
WPBakery Page Builder |   | by Michael M - WPBakery.com – 6.1
Klarna Checkout for WooCommerce |   | by Krokedil – 2.0.3
Klarna Order Management for WooCommerce |   | by klarna, krokedil – 1.5.0 – Not tested with the active version of WooCommerce
MC4WP: Mailchimp for WordPress |   | by ibericode – 4.7.5
MC4WP: Mailchimp Top Bar |   | by ibericode – 1.5.2
MB ImageChimp RSS Feed Enhancer |   | by Mikkel Breum – 1.0
MC4WP: WPML compatibility |   | by ibericode – 1.0.1
PixelYourSite |   | by PixelYourSite – 7.1.5
Popup Maker |   | by Popup Maker – 1.9.1
Royal Core |   | by 8theme – 1.1.4
Search By SKU - for Woocommerce |   | by Matthew Lawson – 0.6.1 – Not tested with the active version of WooCommerce
Shoppable Social Media Galleries by SNPT |   | by Snapppt – 1.1.7
Ultimate Social Media PLUS |   | by social share pro – 3.3.3
W3 Total Cache |   | by BoldGrid – 0.13.1
WooCommerce Product Feed |   | by WebAppick – 3.3.3
WooCommerce Bulk Edit Product Variations |   | by matterico_themes – 2.5.0 – Not tested with the active version of WooCommerce
WooCommerce Print Invoice & Delivery Note |   | by Tyche Softwares – 4.5.3 – Not tested with the active version of WooCommerce
WooCommerce Extra Product Sorting Options |   | by SkyVerge – 2.8.2
WooCommerce Stripe Gateway |   | by WooCommerce – 4.3.2
WooCommerce Multilingual |   | by OnTheGoSystems – 4.7.9 – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons |   | by WooCommerce – 3.0.25 – 3.0.26 is available
WooCommerce |   | by Automattic – 3.9.3 – 4.0.0 is available
Wordfence Security |   | by Wordfence – 7.4.6
Yoast SEO |   | by Team Yoast – 13.2
WP Mail SMTP Plugin by Mail Bank |   | by Tech Banker – 4.0.10
Redirection for Contact Form 7 |   | by Query Solutions – 1.3.5
WPML Media |   | by OnTheGoSystems – 2.5.5
WPML Sticky Links |   | by OnTheGoSystems – 1.5.1
WPML String Translation |   | by OnTheGoSystems – 3.0.7
WPML Translation Management |   | by OnTheGoSystems – 2.9.5
YITH WooCommerce Wishlist |   | by YITH – 3.0.9

I believe I have seen some error regarding this one:
WooCommerce Product Feed |   | by WebAppick – 3.3.3

Should I deactivate that and activate Mailchimp for Wocommerce to see if that makes it Mailchimp  for Woocommerce work? 

Thanks!

**Comment by rrennick** [comment]
> MC4WP: Mailchimp for WordPress

There is an official plugin https://wordpress.org/plugins/mailchimp-for-woocommerce/ . I wasn't aware there was a second one. In my previous comments I was referring to the official one. Your best bet is to go through conflict testing to find the problem plugin(s).

**Comment by kroken123** [comment]
I have the same issue, how did you solve this?
