### ISSUE TITLE
3.0.1: possible plugin conflict with `WPSEO_Link_Watcher::save_post()`

### ISSUE THREAD

**Issue by lkraav** [woocommerce/action-scheduler#515]
After installing `woocommerce-subscriptions-3.0.3`, which still ships `action-scheduler-3.0.1`:

```
$ wp action-scheduler migrate
...
...
...
Warning: Attempting to reduce used memory...
Migrating 100 actions  75 % [================================================================================================================>                                     ] 0:04 / 7:59
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 6787
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 6787
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 6787
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 6792
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 6793
Notice: Trying to get property 'ID' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 6797
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 7038
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-includes/theme.php on line 3094
Notice: Trying to get property 'post_type' of non-object in /home/convers/deploy/plugins/sensei-lms/releases/20200213.164733-leho/includes/class-sensei-posttypes.php on line 990
Notice: Trying to get property 'ID' of non-object in /home/convers/deploy/plugins/sensei-lms/releases/20200213.164733-leho/includes/class-sensei-teacher.php on line 889
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-content/plugins/woocommerce/includes/class-wc-post-data.php on line 109
Notice: Trying to get property 'post_type' of non-object in /home/convers/deploy/plugins/badgeos/releases/20200131.102324-leho/includes/achievement-functions.php on line 849
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-content/plugins/stream/connectors/class-connector-woocommerce.php on line 299
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-includes/theme.php on line 3323
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 4691
Notice: Trying to get property 'ID' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 4691
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 4095
Notice: Trying to get property 'post_name' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 6246
Notice: Trying to get property 'post_status' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 6251
Notice: Trying to get property 'post_date' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 6289
Notice: Trying to get property 'post_status' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 6295
Notice: Trying to get property 'post_status' of non-object in /home/convers/public_html/institute/wp-content/plugins/public-post-preview/public-post-preview.php on line 359
Notice: Trying to get property 'post_type' of non-object in /home/convers/public_html/institute/wp-includes/post.php on line 4133
Notice: Trying to get property 'post_content' of non-object in /home/convers/public_html/institute/wp-content/plugins/fv-wordpress-flowplayer/models/db.php on line 1471
Fatal error: Uncaught TypeError: Argument 2 passed to WPSEO_Link_Watcher::save_post() must be an instance of WP_Post, null given, called in /home/convers/public_html/institute/wp-includes/class-wp-hook.php on line 289 and defined in /home/convers/public_html/institute/wp-content/plugins/wordpress-seo-premium/admin/links/class-link-watcher.php:47
Stack trace:
#0 /home/convers/public_html/institute/wp-includes/class-wp-hook.php(289): WPSEO_Link_Watcher->save_post(2319291, NULL)
#1 /home/convers/public_html/institute/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/convers/public_html/institute/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/convers/public_html/institute/wp-includes/post.php(4144): do_action('save_post', 2319291, NULL, true)
#4 /home/convers/public_html/institute/wp-includes/post.php(4235): wp_insert_post(Array, false)
#5 /home/convers/public_html/institute/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/data-stores/Acti in /home/convers/public_html/institute/wp-content/plugins/wordpress-seo-premium/admin/links/class-link-watcher.php on line 47
Error: There has been a critical error on your website.Learn more about debugging in WordPress. There has been a critical error on your website.
```

Crashing class is in `wordpress-seo-premium-13.1`.

Crashed in the middle of a migration session with the above. Not sure what to make of it off the bat. I repeated `migrate` command and it's continuing (thus far).

Your thoughts?

**Comment by rrennick** [comment]
> Your thoughts?

@lkraav Too bad we don't have the line number in 
```#5 /home/convers/public_html/institute/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/data-stores/Acti in```

as that would give an indication of what AS was doing at the time. Could you let us know if it happens again during the migration?

**Comment by lkraav** [comment]
Indeed, I see the line cut off now as well.

It did not repeat itself for whatever reason, and second run reached "Migration complete" message.

**Comment by lkraav** [comment]
I think it has to be https://github.com/woocommerce/woocommerce-subscriptions/blob/3.0.3/includes/libraries/action-scheduler/classes/data-stores/ActionScheduler_wpPostStore.php#L52 since it's the only `wp_insert_post()` call in this directory:

```
[convers@pill2 ~/public_html/institute/wp-content/plugins/woocommerce-subscriptions/includes/libraries/action-scheduler/classes/data-stores]# ack --php wp_insert_post
ActionScheduler_wpPostStore.php
42:             add_filter( 'wp_insert_post_data', array( $this, 'filter_insert_post_data' ), 10, 1 );
52:             $post_id = wp_insert_post($post_array);
58:             remove_filter( 'wp_insert_post_data', array( $this, 'filter_insert_post_data' ), 10 );
775:            add_filter( 'wp_insert_post_data', array( $this, 'filter_insert_post_data' ), 10, 1 );
781:            remove_filter( 'wp_insert_post_data', array( $this, 'filter_insert_post_data' ), 10 );
```

**Comment by rrennick** [comment]
Oh, looking at the stack trace it's `wp_insert_post` that's calling the `save_post` action not AS. I haven't looked but I'm not sure how the core function would call the hook without all the parameters.

**Comment by rrennick** [comment]
I'm going to close this for now. If someone encounters this issue again, please let us know and we can re-open the issue.
