### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by rrennick** [woocommerce/action-scheduler#619]
PHP 8 is due for release in November 2020. We'll need to confirm compatibility on or before the release date.

**Related pull requests:**

- [x] https://github.com/woocommerce/action-scheduler/pull/626 - Fix unit tests infrastructure and adapt tests to PHP 8
- [x] https://github.com/woocommerce/action-scheduler/pull/632 - Set the PHP version to 7.1 in composer.json for PHP 8 compatibility

Checked items are already merged.

**Comment by strarsis** [comment]
Also when using the WP CLI:
````
Fatal error: Uncaught Error: Class "WP_CLI" not found in /srv/www/web/app/plugins/action-scheduler/classes/abstracts/ActionScheduler.php:168
Stack trace:
#0 /srv/www/web/app/plugins/action-scheduler/action-scheduler.php(44): ActionScheduler::init('/srv/www/web/ap...')
#1 /srv/www/web/app/plugins/action-scheduler/classes/ActionScheduler_Versions.php(59): action_scheduler_initialize_3_dot_1_dot_6()
#2 /srv/www/web/wp/wp-includes/class-wp-hook.php(285): ActionScheduler_Versions::initialize_latest_version()
#3 /srv/www/web/wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#4 /srv/www/web/wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /srv/www/web/wp/wp-settings.php(409): do_action('plugins_loaded')
#6 phar:///bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require('/srv/www/web/wp...')
#7 phar:///bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#8 phar:///bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#9 phar:///bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#10 phar:///bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#11 phar:///bin/wp-cli.phar/php/boot-phar.php(11): include('phar:///bin/wp-...')
#12 /bin/wp-cli.phar(4): include('phar:///bin/wp-...')
#13 {main}
  thrown in /srv/www/web/app/plugins/action-scheduler/classes/abstracts/ActionScheduler.php on line 168
````

**Comment by peterfabian** [comment]
Both items have been merged now, do you think we can close it, @rrennick ?

**Comment by rrennick** [comment]
Sure @peterfabian
