### ISSUE TITLE
Error in action scheduler line 675 how to debug ?

### ISSUE THREAD

**Issue by dummys** [woocommerce/action-scheduler#704]
Hi, we have the following error in our woocommerce:
I don't know if it's related, but one of our product went out of stock for customer, but we still have many items to sell. We don't know why the product get out of stock suddenly, it's not the first time we have this. It happend time to times and I don't know what trigger it ...

```
2021-05-31T11:01:49+00:00 CRITICAL Uncaught RuntimeException: Impossible de demander des actions. Erreur de la base de données. in /home/httpd/vhosts//wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:675
Stack trace:
#0 /home/httpd/vhosts/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php(599): ActionScheduler_DBStore->claim_actions(437938, 25, NULL, Array, '')
#1 /home/httpd/vhosts/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(153): ActionScheduler_DBStore->stake_claim(25)
#2 /home/httpd/vhosts/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueRunner.php(132): ActionScheduler_QueueRunner->do_batch(25, 'Async Request')
#3 /home/httpd/vhosts/wp-includes/class-wp-hook.php(292): ActionScheduler_QueueRunner->run('Async Request')
#4 /home/httpd/vh dans /home/httpd/vhosts/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php à la ligne 675
```
System report:
```
`
### WordPress Environment ###

WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.0
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.18
PHP Post Max Size: 512 Mo
PHP Time Limit: 60
PHP Max Input Vars: 200000
cURL Version: 7.75.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.28-MariaDB
Max Upload Size: 512 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.3.0
WC Database Prefix: wp_
Taille totale de la base de données: 508.94MB
Taille de la base de données: 288.29MB
Taille de l’index: 220.65MB
wp_woocommerce_sessions: Données : 0.08MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 5.52MB + Index : 2.52MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 33.56MB + Index : 36.09MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
ps_sr19_customer: Données : 1.52MB + Index : 2.50MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 3.02MB + Index : 1.22MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 2.02MB + Index : 1.28MB + Moteur InnoDB
wp_aelia_dismissed_messages: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_commentmeta: Données : 0.14MB + Index : 0.17MB + Moteur InnoDB
wp_comments: Données : 37.02MB + Index : 24.09MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_mailchimp_carts: Données : 0.20MB + Index : 0.00MB + Moteur InnoDB
wp_mailchimp_jobs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_options: Données : 5.19MB + Index : 1.16MB + Moteur InnoDB
wp_pimwick_gift_card: Données : 0.08MB + Index : 0.05MB + Moteur InnoDB
wp_pimwick_gift_card_activity: Données : 0.23MB + Index : 0.06MB + Moteur InnoDB
wp_postmeta: Données : 86.36MB + Index : 87.45MB + Moteur InnoDB
wp_posts: Données : 60.48MB + Index : 22.34MB + Moteur InnoDB
wp_termmeta: Données : 1.52MB + Index : 0.61MB + Moteur InnoDB
wp_terms: Données : 0.22MB + Index : 0.33MB + Moteur InnoDB
wp_term_relationships: Données : 6.06MB + Index : 3.17MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.33MB + Index : 0.34MB + Moteur InnoDB
wp_usermeta: Données : 21.55MB + Index : 23.09MB + Moteur InnoDB
wp_users: Données : 1.52MB + Index : 1.13MB + Moteur InnoDB
wp_wcpdf_invoice_number: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 1.52MB + Index : 0.63MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 3.52MB + Index : 5.02MB + Moteur InnoDB
wp_wc_order_stats: Données : 2.52MB + Index : 3.44MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 1.52MB + Index : 1.94MB + Moteur InnoDB
wp_wc_postfinancecheckout_attribute_options: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_postfinancecheckout_completion_job: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_postfinancecheckout_method_config: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_postfinancecheckout_refund_job: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_postfinancecheckout_token_info: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_postfinancecheckout_transaction_info: Données : 0.52MB + Index : 0.03MB + Moteur InnoDB
wp_wc_postfinancecheckout_void_job: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.31MB + Index : 0.52MB + Moteur InnoDB
wp_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wfblockediplog: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wfblocks7: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wfconfig: Données : 2.25MB + Index : 0.00MB + Moteur InnoDB
wp_wfcrawlers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wffilechanges: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wffilemods: Données : 4.52MB + Index : 0.00MB + Moteur InnoDB
wp_wfhits: Données : 1.02MB + Index : 0.20MB + Moteur InnoDB
wp_wfhoover: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wfissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wfknownfilelist: Données : 2.52MB + Index : 0.00MB + Moteur InnoDB
wp_wflivetraffichuman: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wflocs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wflogins: Données : 0.36MB + Index : 0.16MB + Moteur InnoDB
wp_wfls_2fa_secrets: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wfls_settings: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wfnotifications: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wfpendingissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wfreversecache: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wfsnipcache: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wfstatus: Données : 0.13MB + Index : 0.11MB + Moteur InnoDB
wp_wftrafficrates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_yith_wapo_groups: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_yith_wapo_types: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB

### Post Type Counts ###

ajde_events: 33
attachment: 1042
custom_css: 2
evo-tix: 200
global_product_addon: 6
nav_menu_item: 16
page: 36
polylang_mo: 3
post: 3
product: 675
product_variation: 1709
revision: 427
shop_coupon: 579
shop_order: 22118
shop_order_refund: 237
sumo_pp_cron_jobs: 120
sumo_pp_masterlog: 773
sumo_pp_payments: 118
tabwoo: 1
tm_global_cp: 6
wp_block: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Polylang: par WP SYNTEX – 3.0.4
Query Monitor: par John Blackbourn – 3.7.1
Contact Form 7: par Takayuki Miyoshi – 5.4.1
WooCommerce Discontinued Products: par Leon @ 211J – 1.1.5
Easy WP SMTP: par wpecommerce
alexanderfoxc – 1.4.6

EventON: par AshanJay – 3.1.4
Oubliez les codes courts de boutons: par Designs & Code – 2.1.2
Fr Multi Bank Transfer Payment Gateways for WooCommerce: par Fahri Rusliyadi – 1.1.0
HandMade WooCommerce Order Status Control: par HandMade Connections – 1.4
Mailchimp for WooCommerce: par Mailchimp – 2.5.1
PW WooCommerce Gift Cards Pro: par Pimwick
LLC – 1.306

Redis Object Cache: par Till Krüss – 2.0.18
Safe SVG: par Daryll Doyle – 1.9.9
WooCommerce Side Cart: par XootiX – 2.1
SUMO Payment Plans: par Fantastic Plugins – 7.3
Under Construction: par WebFactory Ltd – 3.88
UpdraftPlus - Sauvegarde/Restauration: par UpdraftPlus.Com
DavidAnderson – 2.16.58.25

Aelia Foundation Classes for WooCommerce: par Aelia – 2.1.8.210518
WooCommerce PostFinance Checkout: par wallee AG – 1.5.2
WooCommerce Admin: par WooCommerce – 2.3.0
Aelia Currency Switcher for WooCommerce: par Aelia – 4.10.2.210513
WooCommerce PDF Invoices & Packing Slips: par Ewout Fernhout – 2.8.3
WooCommerce TM Extra Product Options: par themeComplete – 5.0.12.12
WooCommerce: par Automattic – 5.3.0
Wordfence Security: par Wordfence – 7.5.3
WordPress User Extra Fields: par Lagudi Domenico – 14.7

### Inactive Plugins (3) ###

Hyyan WooCommerce Polylang Integration: par Hyyan Abo Fakher – 1.5.0
TabWoo - Extra Tabs Plugin for WooCommerce: par AccessPress Themes – 1.0.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Must Use Plugins (1) ###

akeeba-backup-coreupdate.php: par  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #1936 - /boutique/
Panier: #8 - /cart/
Commander: #9 - /checkout/
Mon compte: #10 - /my-account/
Conditions générales de vente et d’utilisation: #3 - /privacy-policy/

### Theme ###

Name: YOOtheme Child
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: YOOtheme
Parent Theme Version: 2.4.14 – 2.4.17 est disponible
Parent Theme Author URL: https://yootheme.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Annulé: 5
Oldest: 2021-05-01 20:56:44 +0000
Newest: 2021-05-22 17:06:39 +0000

Terminé: 4 702
Oldest: 2021-05-01 20:56:44 +0000
Newest: 2021-06-01 20:28:08 +0000

Échoué: 1
Oldest: –
Newest: –

En attente: 3
Oldest: 2021-06-01 21:03:14 +0000
Newest: 2021-06-01 21:03:14 +0000


### Status report information ###

Generated at: 2021-06-01 20:36:54 +00:00
`
```

**Comment by JVDL-1** [comment]
Hey @dummys,

I've got exactly the same error on our site, did you find a solution already? Also wondering how to debug it.

Thank you.

**Comment by dummys** [comment]
for now I have no fucking idea to be honest. I still try to understand. But I think people from woocommerce are not ready to help ...

**Comment by barryhughes** [comment]
📝 For my own ref: _"Impossible de demander des actions. Erreur de la base de données."_ == _"Unable to claim actions. Database error."_

---

@dummys it's hard to know what exactly caused this, but your Action Scheduler tables don't look like they are particularly full so I don't think this is a problem being caused by an avalanche of scheduled actions, or anything like that:

```
wp_actionscheduler_actions: Données : 3.02MB + Index : 1.22MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 2.02MB + Index : 1.28MB + Moteur InnoDB
```

How often are you seeing this error, exactly?

**Comment by dummys** [comment]
We see it like every 2 or 3 days. I don't know if it's related, but we suffer from weird bug where variable product get out of stock, but in fact, there is lot remaining... It happend without any action I guess. I'm still trying to understand where is the cuprit, that's why I look everywhere.

**Comment by JVDL-1** [comment]
@dummys I've managed to fix the issue on our side, but I noticed we got deadlocks on the database which caused the issue. I've updated the action scheduler to the newest version (3.2.0) by installing the plugin from the WordPress library which I believe helped to fix the issue on our side, but i'm not fully sure because we also did some other things. So maybe it's worth trying, but please check the change log because it seems to generate an index and I don't know if you can downgrade to the older version of action scheduler.

**Comment by barryhughes** [comment]
True: 3.2.0 should reduce the risk of deadlocks in many cases (though doesn't entirely eliminate the potential for them to happen). As a next step—working with your hosting provider as needed—I'd suggest ensuring you can access the MySQL logs and, next time you notice the _"Impossible de demander des actions"_ error, check and see if there is a corresponding MySQL error.

* If the error relates to deadlocks, then you could try @JVDL-1's suggestion re Action Scheduler 3.2.0 (and I'll quickly note here that this will anyway be included in a future WooCommerce update).
* If the error does not relate to deadlocks, please update this issue with details of the error.
