### ISSUE TITLE
Call to undefined function as_next_scheduled_action()

### ISSUE THREAD

**Issue by olegabr** [woocommerce/action-scheduler#730]
If action-scheduler is used in a [plugin](https://wordpress.org/plugins/ethereum-wallet/) on a site running WooCommerce 5.5.0, site crashed with error `Call to undefined function as_next_scheduled_action()`

I've got 10+ reports from plugin users today :-)

**Comment by barryhughes** [comment]
I'm not immediately able to replicate:

![active-plugins](https://user-images.githubusercontent.com/3594411/125658862-cdc3de13-0837-4959-ab43-32da17b541e8.png)

Is anything besides Ethereum Wallet 2.8.0 and WooCommerce 5.5.0 required to see the problem, and can you provide some steps-to-replicate in case I'm missing something? Any other potentially relevant information you can provide (such as the versions of PHP and WP are you using, or if opting in or out of Freemius impacts the problem) appreciated.

**Comment by olegabr** [comment]
@barryhughes Thank you for your reply. I've updated free plugin version to the latest one. update and try again please.

**Comment by barryhughes** [comment]
@olegabr—this feels _verrry_ similar to #724: can you repeat the same treatment we used there?

Interestingly, in my own testing I find if I apply that same fix as last time not only does it resolve the problem, but if I subsequently _revert_ the fix the problem still doesn't come back. This tends to make me think the issue is somehow related to the way Freemius works (and that, once some sort of flag is set, whatever process triggers the problem is not repeated).

My provisional recommendation though would be continuing to apply the same fix we used last time any time you rebuild or refactor your main plugin file. Whatever is causing this would seem to be atypical and not a direct result of anything Action Scheduler does (unless, of course, it can be distilled down to a something that can be replicated with a simple test plugin that does not involve that other library).

**Comment by olegabr** [comment]
@barryhughes  Yes, it helped, thank you. I've totally forgot the same issue with another plugin, sorry.
But I still believe that the https://github.com/woocommerce/action-scheduler/pull/731 PR is needed, since now [class_exists](https://www.php.net/manual/en/function.class-exists.php) calls have side effects they should not have:

```
class_exists(string $class, bool $autoload = true): bool
autoload
Whether to call __autoload by default.
```

This PR makes them not to load the class tested to not break checks in another plugins.

**Comment by olegabr** [comment]
@barryhughes Just found that premium version still fails on a plugin activation:
```
 Fatal error: Uncaught Error: Call to undefined function as_next_scheduled_action()
in /var/www/html/wp-content/plugins/ethereum-wallet-premium/ethereum-wallet.php on line 1162
```

I've compared it with free version line by one and see no reason why. Send me your email to support at ethereumico dot io for a premium plugin license please.

For now I have this workaround for the premium version:

```
if ( ! class_exists( 'ActionScheduler', false ) || ! ActionScheduler::is_initialized() ) {
    require_once( dirname( __FILE__ ) . '/vendor/woocommerce/action-scheduler/classes/abstracts/ActionScheduler.php' );
    ActionScheduler::init( dirname( __FILE__ ) . '/vendor/woocommerce/action-scheduler/action-scheduler.php' );
}

// call as_next_scheduled_action or any other as_ function here
```

**Comment by olegabr** [comment]
The reason why only premium version crashes now, is the the free version does not call `as_next_scheduled_action` or any other `as_` function :-)

**Comment by olegabr** [comment]
Just updated my another site to the latest WC 5.5.1 and got this fatal error:

```
2021/07/15 08:38:15 [error] 536891#536891: *255300 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function as_next_scheduled_action() in /var/www/html2/wp-content/plugins/woocommerce/includes/queue/class-wc-action-queue.php:127
Stack trace:
#0 /var/www/html2/wp-content/plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php(294): WC_Action_Queue->get_next()
#1 /var/www/html2/wp-includes/class-wp-hook.php(292): WC_Notes_Run_Db_Update::show_reminder()
#2 /var/www/html2/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#3 /var/www/html2/wp-includes/plugin.php(484): WP_Hook->do_action()
#4 /var/www/html2/wp-admin/includes/class-wp-screen.php(421): do_action()
#5 /var/www/html2/wp-admin/includes/screen.php(240): WP_Screen->set_current_screen()
#6 /var/www/html2/wp-admin/admin.php(212): set_current_screen()
#7 /var/www/html2/wp-admin/update-core.php(10): require_once('/var/www/html2/...')
#8 {main}
  thrown in /var/www/html2/wp-content/plugins/woocommerce/includes/queue/class-wc-action-queue.php on line 127" while reading response header from upstream, client: 212.74.202.71, server: guestauthoraffiliate.com, request: "GET /wp-admin/update-core.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "guestauthoraffiliate.com", referrer: "https://guestauthoraffiliate.com/wp-admin/update.php?action=update-selected&plugins=woocommerce%2Fwoocommerce.php&_wpnonce=172db245ff"
```

The only my plugin I had here is https://wordpress.org/plugins/ether-and-erc20-tokens-woocommerce-payment-gateway/

After renaming it's folder site works again. That is exactly why this PR is needed - not only woocommerce can crash other plugins, other plugins can crash woocommerce, if they were loaded first I assume.

**Comment by olegabr** [comment]
Fresh report from a client - "now I try to remove some order in woocommerce. it will occur error:"

```
2021-07-15T09:19:02+00:00 CRITICAL Uncaught Error: Call to undefined function as_get_scheduled_actions() in /var/www/html/wp-content/plugins/woocommerce/includes/queue/class-wc-action-queue.php:158
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/SchedulerTraits.php(185): WC_Action_Queue->search()
#1 /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/SchedulerTraits.php(297): Automattic\WooCommerce\Admin\Schedulers\ImportScheduler::has_existing_jobs()
#2 /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/OrdersScheduler.php(130): Automattic\WooCommerce\Admin\Schedulers\ImportScheduler::schedule_action()
#3 /var/www/html/wp-includes/class-wp-hook.php(294): Automattic\WooCommerce\Admin\Schedulers\OrdersScheduler::possibly_schedule_import()
#4 /var/www/html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#5 /var/www/html/wp-includes/plugin.php(484): WP_Hook->do_action()
#6 /var/www/html/wp-includes/post.php(43 in /var/www/html/wp-content/plugins/woocommerce/includes/queue/class-wc-action-queue.php on line 158
```

**Comment by olegabr** [comment]
For now my plan is to fork the action-scheduler library, apply this PR to it and use this forked library in my plugins to not break woocommerce. And use the workaround above to not let woocommerce break my plugins. Wierd, yeah :-)

**Comment by barryhughes** [comment]
OK, well that sounds like a reasonable interim step.

Regarding the patch you wrote (to avoid triggering autoloaders during `class_exists()` checks): does your testing indicate that change successfully resolves this issue?

**Comment by olegabr** [comment]
Yes, it can be tested on this free plugin: https://wordpress.org/plugins/ether-and-erc20-tokens-woocommerce-payment-gateway/
The v4.8.10 is not patched. It crashes site as described above. The v4.8.12 is patched and works with no problems.

**Comment by olegabr** [comment]
New report for the same issue for another my Ethereum Wallet plugin: https://wordpress.org/support/topic/fatal-error-after-update-rankmath/
Just to inform other users who may face it also.

**Comment by leewillis77** [comment]
Adding my voice to this. We shipped an extension update on Friday last week that bundles AS v3.3.0. That works fine on a "standard" WooCommerce install (tested with WC 5.7.x which bundles AS v3.2.1). 

However, we're receiving support tickets from users where it appears that v3.3.0 isn't being loaded (`Call to undefined function as_next_scheduled_action()`).

It appears this happens where v3.1.6* of AS is bundled by another plugin on the site (In the cases we've seen so far, the culprit is WooCommerce Smart Coupons).

In this case, it looks like v3.3.0 isn't loaded properly and we get undefined function errors. 

* Other versions may also be affected, I haven't had chance to test.

**Comment by leewillis77** [comment]
There's a ZIP here that contains two stripped down plugins that illustrate the issue. To reproduce the issue install, and activate both of these on a fresh WordPress install
[action-scheduler-730.zip](https://github.com/woocommerce/action-scheduler/files/7237622/action-scheduler-730.zip)

## uses-as-3.1.6
Requires version 3.1.6 of action scheduler _at plugins_loaded / -1_ and does nothing else

## uses-as-3.3.0
Requires version 3.3.0 of action scheduled as the plugin is loaded e.g. straight include in plugin file, then attempts (on _init_) to call `as_has_scheduled_action`

This yields the error:
`Call to undefined function as_has_scheduled_action() in /Users/lee/sites/as-test/wp-content/plugins/uses-as-3.3.0/uses-as-3.3.0.php`

## Notes
- Updating uses-as-3.1.6 to AS v3.2.0 does *not* resolve the error
- Updating uses-as-3.1.6 to AS v3.2.1 *does* resolves the error
- Amending uses-as-3.1.6 to include action-scheduler directly rather than on plugins_loaded/-1 resolves the error

**Comment by barryhughes** [comment]
Thank you, I'm able to replicate with those steps.

- Feels like a continuation—or another facet—of [this problem](https://github.com/woocommerce/action-scheduler/issues/714).
- At least in my own testing, the fix proposed by @olegabr doesn't resolve this (and I'm noting that as a reminder that we shouldn't necessarily close this even after resolving the problem identified in the above two comments).

**Comment by barryhughes** [comment]
Couple notes:

- If a plugin uses the `plugins_loaded:-10` strategy to load an earlier version of Action Scheduler, like 3.1.6, then [this block is executed](https://github.com/woocommerce/action-scheduler/blob/3.1.6/action-scheduler.php#L48-L52).
- [This line](https://github.com/woocommerce/action-scheduler/blob/3.1.6/action-scheduler.php#L49) in particular means we're going to initialize 3.1.6 right away instead of waiting to see what other versions exist (probably, this is meant to be a call to the registration function and not the initialization function ... but even if that was fixed we'd hit the same problem because of [this line](https://github.com/woocommerce/action-scheduler/blob/3.1.6/action-scheduler.php#L51)—as other versions of the library still haven't been registered at this point, as in most cases they will wait until `plugins_loaded:0` to register).
- It's because of this (3.1.6 is the loaded version, but functions such as `as_has_scheduled_action()` are not available until 3.3.0) that we will hit the issue noted above.

**Comment by olegabr** [comment]
Fresh report from a client. He has the https://ethereumico.io/product/wordpress-ethereum-wallet-plugin/ installed, and has an issue with another plugin (https://wordpress.org/plugins/seo-by-rank-math/) using action scheduler internally: 

> im still facing the issue when activating Rankmath, a critical error is displayed, the front-end is still accesible but not the wp-admin. I have to deacitavate the plugin through FTP to re-gain acces to wp-admin.

![ethereum_wallet_bug_2_rankmath](https://user-images.githubusercontent.com/2850808/135567956-e14c789a-a1e4-4a16-9fc9-3820a7cead78.png)

**Comment by olegabr** [comment]
I've updated the action-scheduler version in my plugins to 3.3.0 and tested this free plugin:
https://wordpress.org/plugins/ether-and-erc20-tokens-woocommerce-payment-gateway/

Only one other plugin using the action-scheduler library was activated:  woocommerce

How to reproduce: try to remove or restore order.

I've tried to move the initialization line to the very top of my plugin file with no effect:
```php
require_once dirname( __FILE__ ) . '/vendor/woocommerce/action-scheduler/action-scheduler.php';
```

The error shown:

```
 Fatal error: Uncaught Error: Call to undefined function as_get_scheduled_actions()
in /var/www/html/wp-content/plugins/woocommerce/includes/queue/class-wc-action-queue.php on line 158

Call stack:

WC_Action_Queue::search()
wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/SchedulerTraits.php:185
Automattic\W\A\S\ImportScheduler::has_existing_jobs()
wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/SchedulerTraits.php:297
Automattic\W\A\S\ImportScheduler::schedule_action()
wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Schedulers/OrdersScheduler.php:130
Automattic\W\A\S\OrdersScheduler::possibly_schedule_import()
wp-includes/class-wp-hook.php:305
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:327
WP_Hook::do_action()
wp-includes/plugin.php:470
do_action()
wp-includes/post.php:4468
wp_insert_post()
wp-includes/post.php:4570
wp_update_post()
wp-includes/post.php:3489
wp_untrash_post()
wp-admin/edit.php:149
```

**Comment by barryhughes** [comment]
Current thinking:

- We should merge https://github.com/woocommerce/action-scheduler/pull/731 (and so avoid triggering autoloaders during `class_exists()` checks).
- We should also update our documentation, and explicitly advise against adding Action Scheduler classes to the parent plugin's classmap (as in my previous comment).

**Comment by barryhughes** [comment]
Yes, I saw those entries (but I didn't think they were normally generated without an `autoload.classmap` directive or equivalent.

> Also, if the #731 patch is applied to the 3.3.0 action-scheduler version, it stops break woocommerce in this simple installation example.

Great—that matches my expectations and we'll get that merged, though I can create cases where merging that PR does not solve the problem (it would depend on plugin load order and the version of Action Scheduler being loaded by each plugin).

**Comment by olegabr** [comment]
New reports after last WooCommerce update:

`
/home/ethereumico.io/public_html/wp-content/plugins/action-scheduler/functions.php verursacht. Fehlermeldung: Uncaught Error: Call to undefined method ActionScheduler_ActionFactory::single_unique() in /home/ethereumico.io/public_html/wp-content/plugins/action-scheduler/functions.php:40

Stack trace:

#0 /home/ethereumico.io/public_html/wp-content/plugins/ethereum-wallet-premium/ethereum-wallet.php(665): as_schedule_single_action(1663164077, 'ETHEREUM_WALLET...', Array, 'ethereum-wallet...')
`

After sync with the 3.4.2 tag as used in the WC now:

`
/home/ethereumico.io/public_html/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/functions.php verursacht. Fehlermeldung: Uncaught Error: Call to undefined method ActionScheduler_ActionFactory::single_unique() in /home/ethereumico.io/public_html/wp-content/plugins/seo-by-rank-math/vendor/woocommerce/action-scheduler/functions.php:40

Stack trace:

#0 /home/ethereumico.io/public_html/wp-content/plugins/ethereum-wallet-premium/ethereum-wallet.php(665): as_schedule_single_action(1663179322, 'ETHEREUM_WALLET...', Array, 'ethereum-wallet...')
`

So, looks like all plugins installed should use the same action-scheduler version to eliminate conflicts.

**Comment by barryhughes** [comment]
Hi @olegabr,

Can you create a new issue (this one is closed) and include some steps to replicate? If specific code or a specific plugin is needed alongside WooCommerce, can you also provide details/links as needed?

That will also make it easier for others experiencing this issue to share notes, etc.

Thanks :-)
